language: csharp
notifications:
  email: false
os:
  - linux
mono: none
dotnet: 4.7.1
dist: trusty

env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=1

solution: MiniDatabase.sln
install:
  - dotnet restore
script:
  - dotnet test
