language: csharp
solution: MiniDatabase.sln
install:
  - nuget restore MiniDatabase.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release MiniDatabase.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./DbXunitTests/bin/Release/DbXunitTests.dll