language: csharp
notifications:
  email: false
os:
  - linux
mono: none

solution: MiniDatabase.sln
install:
  - nuget restore MiniDatabase.sln
  - nuget install xunit.runner.console -Version 2.3.1 -OutputDirectory testrunner
script:
  - dotnet build
  - dotnet nest ./DbXunitTests/DbXunitTests.csproj -parallel none -noshadow
