language: csharp
notifications:
  email: false
os:
  - linux

solution: MiniDatabase.sln
install:
  - nuget restore MiniDatabase.sln
  - nuget install xunit.runner.console -Version 2.3.1 -OutputDirectory testrunner
  - chmod +x build.sh
  - chmod +x deploy.sh
script:
  - ./build.sh
after_success:
  - ./deploy.sh
